theme = "showfolio"
languageCode = "en-us"
baseurl = "https://dgoscn.com/"
title = "Somebody Find Diego"


[params]
  name = "Somebody Find Diego"
  description = "This is hugo portfolio based"
  author = "Diego Amaral"
  authorEmail = "diego.amar4l@gmail.com"
  authorImage = "/photo.png"
  autoDarkMode = true

  copyright = "Copyright © 2023 - Diego Amaral · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey I'm Diego Amaral"
  tagline = "Site Reliability Engineer"
  description = "Here, you will find some links and basic info about me"
  contact = "https://dgooscn.thesimple.ink/"

[params.homepage.codepen]
  username = "apvarun"
  pens = ["MQaRKL", "RxodrP", "BmXGdm", "wdVypQ"]

[params.homepage.resume]
  skills = ["AWS", "Kubernetes", "Terraform", "CI/CD", "OpenTelemetry", "Golang", "Distributed Tracing", "Prometheus", "Leadership", "Product Management", "Open source contributor"]

[[params.homepage.resume.work]]
  name = "PicPay"
  role = "Site Reliability Engineer Specialist"
  duration = "2023 - Current"

[[params.homepage.resume.work]]
  name = "C6 Bank"
  role = "Site Reliability Engineer Specialist"
  duration = "2022 - 2023"

[[params.homepage.resume.work]]
  name = "Itaú Unibanco"
  role = "Site Reliability Engineer"
  duration = "2021 - 2022"

[[params.homepage.resume.work]]
  name = "Tembici"
  role = "DevOps Engineer"
  duration = "2020 - 2021"

[[params.homepage.resume.work]]
  name = "Levoo"
  role = "Software Engineer"
  duration = "2019 - 2020"

[[params.homepage.resume.work]]
  name = "MRV Engenharia"
  role = "Software Engineer Consultant"
  duration = "2018 - 2019"

[[params.homepage.resume.work]]
  name = "UFRN"
  role = "Professor Assistant in Security and Computer Networks"
  duration = "2017 - 2018"

[[params.homepage.resume.work]]
  name = "RNP"
  role = "System Administrator Intern"
  duration = "2016 - 2018"

[[params.homepage.resume.work]]
  name = "RoboEduc"
  role = "Educational Robotics Teacher"
  duration = "2014"

[[params.homepage.resume.work]]
  name = "4Soft Jr"
  role = "Software Engineer Intern"
  duration = "2014"

[[params.homepage.resume.courses]]
  name = "Bsc Information Technology - Computer Science"
  provider = "Federal University from Rio Grande do Norte"
  duration = "Feb 2014 - Dez 2019"

[[params.homepage.resume.courses]]
  name = "Digital Product Leadership"
  provider = "TERA"
  duration = "Jun 2019 - Ago 2019"

[params.homepage.social]
  linkedin = "https://www.linkedin.com/in/amaraldude/"
  github = "https://github.com/dgoscn"
  medium = "https://medium.com/@dgoscn"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
