theme = "showfolio"
languageCode = "en-us"
baseurl = "https://example.com"
title = "Somebody Find Diego"


[params]
  name = "Somebody Find Diego"
  description = "This is hugo portfolio based"
  author = "Diego Amaral"
  authorEmail = "diego.amar4l@gmail.com"
  authorImage = "/photo.png"
  autoDarkMode = true

  copyright = "Copyright © 2023 - Diego Amaral · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey 👋 I'm Diego Amaral"
  tagline = "Site Reliability Enginner"
  description = "Here, you will find some links and basic info about me"
  contact = "https://www.linkedin.com/in/amaraldude/"

[params.homepage.codepen]
  username = "apvarun"
  pens = ["MQaRKL", "RxodrP", "BmXGdm", "wdVypQ"]

[params.homepage.resume]
  skills = ["AWS", "Kubernetes", "Terraform", "CI/CD", "OpenTelemetry", "Golang", "Distributed Tracing", "Prometheus", "Leadership", "Product Management", "Open source contributor"]

[[params.homepage.resume.work]]
  name = "C6 Bank"
  role = "Site Reliability Enginner Specialist"
  duration = "Mar 2022 - Feb 2023"

[[params.homepage.resume.work]]
  name = "Itaú Unibanco"
  role = "Site Reliability Enginner"
  duration = "Feb 2021 - Mar 2022"

[[params.homepage.resume.work]]
  name = "Tembici"
  role = "DevOps Enginner"
  duration = "Feb 2020 - Feb 2021"

[[params.homepage.resume.courses]]
  name = "Bsc Information Technology - Computer Science"
  provider = "Federal University from Rio Grande do Norte"
  duration = "Feb 2014 - Dez 2019"

[[params.homepage.resume.courses]]
  name = "Digital Product Leadership"
  provider = "TERA"
  duration = "Jun 2019 - Ago 2019"

[params.homepage.social]
  linkedin = "https://www.linkedin.com/in/amaraldude/"
  github = "https://github.com/dgoscn"
  medium = "https://medium.com/@dgoscn"
  twitter = "https://twitter.com/dgoscn"
  instagram = "https://instagram.com/diego.amrl"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
