input {
  http {
    host => "0.0.0.0"
    port => 5022
    codec => "line"
  }
  beats {
    port => 5044
  }
}

filter {
  prune {
    whitelist_names => [ "message" ]
  }

  mutate {
    gsub => [
      "message", "\\n", "",
      "message", "\\\"", "\"",
      "message", "\\\\", ""
    ]
  }

  json {
    source => "message"
  }

  if [blocked] == "true" {
    drop { }
  }

  mutate {
    remove_field => ["anything_else", "debug_timing", "tags", "browser_info", "profiler"]
  }

  if ![host] =~ /^api\\.(.*)\\.dlocal\\.com$/ {
    drop { }
  }

  translate {
    field => "host"
    destination => "host_normalized"
    dictionary_path => "/usr/share/logstash/patterns/hosts.yml"
    fallback => "unknown"
  }

  mutate {
    lowercase => ["uri"]
  }

  if [uri] =~ /\\/accounts\\/[0-9a-zA-Z]+/ {
    mutate { replace => { "uri" => "/accounts" } }
  }
}

output {
  stdout { codec => rubydebug }
}
