input {
  file {
    path => "/usr/share/logstash/logs/input.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

filter {
  translate {
    field => "[x-login]"
    destination => "[merchant_id]"
    dictionary_path => "/usr/share/logstash/dictionaries/x-login.yaml"
    exact => true
    fallback => "unknown"
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
